AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50

AppBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank: ~
            - Type: string
        password:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Post:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
    properties:
        title:
            - NotBlank: ~
            - Type: string
            - Length:
                min: 4
                max: 50
        content:
            - NotBlank: ~
            - Type: string
            - Length:
                min: 4
                max: 510

AppBundle\Entity\Comment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: content
    properties:
        content:
            - NotBlank: ~
            - Type: string
            - Length:
                min: 4
                max: 510