AppBundle\Entity\Post:
    exclusion_policy: none
    properties:
        id:
            groups: ['users', 'posts', 'comments']
        title:
            groups: ['posts', 'comments']
        content:
            groups: ['posts']
        createdAt:
            groups: ['posts']
        user:
            groups: ['posts']
        email:
            groups: ['posts']
